on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:

name: Weather update

jobs:
  render:
    name: Update data
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          # use Posit's CRAN mirror with precompiled binaries
          use-public-rspm: true
          
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2 # automatically sets up cache
        with:
          packages: |
            any::ggplot2 
            any::rvest
            any::openxlsx2
            any::lubridate
            any::stringr
            any::scales
            any::lubridate
            any::data.table
            any::R.utils
      
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Retrieve data
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 30
          max_attempts: 3
          command: Rscript -e 'source("get_stringmeteo.R")'
          continue_on_error: true
          
     
      - name: Commit new data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update data
        timeout-minutes: 4
